CREATE OR REPLACE FILE FORMAT NYC_TAXI_DB.RAW.PARQUET_FORMAT
    TYPE = PARQUET;

CREATE TABLE NYC_TAXI_DB.RAW.YELLOW_TRIPS
USING TEMPLATE (
    SELECT ARRAY_AGG(
        OBJECT_CONSTRUCT(
            'COLUMN_NAME', COLUMN_NAME,
            'TYPE', TYPE,
            'NULLABLE', NULLABLE
        )
    )
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@NYC_TAXI_DB.RAW.NYC_TAXI_STAGE',
            FILE_FORMAT => 'NYC_TAXI_DB.RAW.PARQUET_FORMAT'
        )
    )
);

COPY INTO NYC_TAXI_DB.RAW.YELLOW_TRIPS
FROM @NYC_TAXI_DB.RAW.NYC_TAXI_STAGE
FILE_FORMAT = (
    FORMAT_NAME = 'NYC_TAXI_DB.RAW.PARQUET_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT COUNT(*)
FROM NYC_TAXI_DB.RAW.YELLOW_TRIPS;
